### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-xyqyr#3]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by c0boo** [comment]
![Screenshot 2022-10-07 at 05 14 57](https://user-images.githubusercontent.com/83968424/194460409-a3433412-cba0-4d1d-b652-aaf61d945153.png)
